---
apiVersion: v1
kind: Pod
metadata:
    name: faker-v2
    namespace: logging
    labels:
        app: faker-v2
spec:
    restartPolicy: Never
    containers:
    - name: faker-v2
      image: 10.0.0.255:5000/gedge-platform/faker:v2.0.0
      #args: ["sh",  "-c", "while true; do sleep 30; done;"]
      imagePullPolicy: Always    
      ports:
      - containerPort: 8080
    nodeSelector:
        kubernetes.io/hostname: ketiops-gpu-node-4
